name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    if: github.repository == 'rameel/sass-utility-generator'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 12

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test (prepublish check)
        run: pnpm test

      - name: Publish to npm
        run: |
          npm_tag=$(node -p "require('./package.json').version.split('+')[0].includes('-') ? 'beta' : 'latest'")
          npm publish --tag "$npm_tag"
